name: DAW_DAM_DEV
services:
  java:
    image: mcr.microsoft.com/vscode/devcontainers/java:21
    container_name: Java
    volumes:
      - ..:/workspace:cached
      - ./.gitconfig:/home/vscode/.gitconfig:cached
    command: |
      bash -c "
        # Eliminar antiguos elementos
        rm -rf /workspace/._recursos

        # Mantener el contenedor en ejecución
        sleep infinity
      "
    environment:
      - JAVA_HOME=/usr/local/openjdk-11
    networks:
      - devnetwork

  python:
    image: python:3.9
    container_name: Python
    volumes:
      - ..:/workspace:cached
    command: sleep infinity
    networks:
      - devnetwork

  php:
    image: php:8.0-apache
    container_name: PHP
    volumes:
      - ..:/var/www/html:cached
    ports:
      - "80:80"
    command: |
      bash -c "
        docker-php-ext-install mysqli
        apache2-foreground
      "
    networks:
      - devnetwork

  mysql:
    image: mysql:8.0
    container_name: MySQL
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: dawdb
      MYSQL_PASSWORD: root
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3456:3306"
    networks:
      - devnetwork

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: PHPmyAdmin
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: root
      UPLOAD_LIMIT: 64M
    depends_on:
      - mysql
    networks:
      - devnetwork

networks:
  devnetwork:

volumes:
  mysql-data:
